package com.pos10.util

object SingletonObject {
    var isEdit:Boolean =false
    var companyName: String=""
    var typeOfBusiness: String=""
    var country: String=""
    var account_username: String=""
    var contact_number: String=""
    var country_code: String=""
    var email: String=""
    var firstName: String=""
    var lastName: String=""
    var title: String=""

    var commercial_registration_number: String=""
    var country_address: String=""
    var mobile_number: String=""
    var permanent_establishment_number: String=""
    var street_line_1: String=""
    var street_line_2: String=""
    var taxpayer_id_number: String=""
    var vat_id_number: String=""
    var website: String=""
    var zip_code: String=""

    var accountHolderName: String = ""
    var accountHolderAddress: String = ""
    var bankAccountNumber: String = ""
    var iban: String = ""
    var confirmBankAccountNumber: String = ""
    var routingNumber: String = ""
    var swiftCode: String = ""

    var uploadBusinessRegistration1:String=""
    var uploadBusinessRegistration2:String=""
    var uploadAddressProof1:String=""
    var uploadAddressProof2:String=""
    var uploadIdentityProof1:String=""
    var uploadIdentityProof2:String=""

    fun clear() {
        companyName = ""
        typeOfBusiness = ""
        country = ""
        account_username = ""
        contact_number = ""
        country_code = ""
        email = ""
        firstName = ""
        lastName = ""
        title = ""

         commercial_registration_number=""
         country_address=""
         mobile_number=""
         permanent_establishment_number=""
         street_line_1=""
         street_line_2=""
         taxpayer_id_number=""
         vat_id_number=""
         website=""
         zip_code=""

        accountHolderName = ""
        accountHolderAddress = ""
        bankAccountNumber = ""
        confirmBankAccountNumber = ""
        routingNumber = ""
        swiftCode = ""

         uploadBusinessRegistration1=""
         uploadBusinessRegistration2=""
         uploadAddressProof1=""
         uploadAddressProof2=""
         uploadIdentityProof1=""
         uploadIdentityProof2=""
    }
}